### ISSUE TITLE
Individual report algorithm

### ISSUE THREAD

**Issue by cankisagun** [enigmampc/SafeTrace#17]
This issue captures our current thinking around privacy preserving computations and the input data (JSON form for now).

- Ingest JSON data ([sample data here](https://drive.google.com/file/d/1iL_GlfDHxbr-XnXVvWjUccK92CTCA3z9/view?usp=sharing)) from Google maps. 
- Individual matches are triggered by Place Visit (lat, lon + a radius based on feedback - _ie. +/- 10 ft_) and time window (based on feedback - _i.e + 0-3 hours_)
- Return results to the web UI to be shown to the end user in the following format: <<lat/lon, time, date>>

Open question:
- [ ] do we want to exclude certain locations like home address?
- [ ] does it make sense to treat park lower risk than grocery store?

**Comment by ainsleys** [comment]
@cankisagun can you clarify the requirements for the MVP? We should probably make a new issue that refers only to those goals. We can reference this issue for longer discussion, but for the purpose of tracking our progress to MVP I'd prefer it to be complete & concise. 

I propose:

Rust code that runs inside the enclave, takes inputs of `userID`, `infectionStatus`, `latitude`, `longitude`, `time`, and `duration`. 
Code compares `latitude` and `longitude` between submitted user data and all user data which has been submitted and has a positive test result to find matches within 4m and 24hours. 
Code returns a list of locations and dates where user "matched" with someone who has tested positive. 

Other things we have discussed:
- including a timestamp in returned matches (i.e., Rochester Park on 3/22/20 at 2pm vs Rochester Park 3/22/20)
- displaying matches with symptomatic but not positive users
- omitting certain locations based on duration and time of stay
- "risk" assessment (i.e., introducing time-based decay of "risk" or a "risk score" based on other factors). 

Are any of these things to be included in the MVP? cc @cankisagun

**Comment by FishmanL** [comment]
You're going to want (for DP purposes) to add random noise to the distance between users before checking for a match, see e.g. https://adaptivedataanalysis.files.wordpress.com/2017/11/lect12.pdf for a version of this

**Comment by ainsleys** [comment]
Thanks @FishmanL , agree we need to consider the best way to ensure privacy either via noise or limits on granularity of reporting. For MVP that is out of scope-- see https://github.com/enigmampc/SafeTrace/issues/24 for MVP requirements for the matching algorithm. Moving this issue off the project board for now.

**Comment by ainsleys** [comment]
This has been implemented for MVP, but noting that improvements are now tracked in #33
