### ISSUE TITLE
User input fields

### ISSUE THREAD

**Issue by cankisagun** [enigmampc/SafeTrace#18]
This issue discusses user data inputs besides the location history. We should use this issue to track these inputs

Current suggestions are:
MVP Scope
From web interface
- Covid test result (yes / no / not tested)
- Covid test result date (not relevant if covid test result answer is not / tested)
- Location history (drag / drop JSON file)

From web DB
- Unique_user_ID that corresponds to the user who's logged in
- Time of submission 

Future work
- People is symptomatic/asymptomatic - may be future work as well
- Future work - we can add severity based on symptom description
- Protective gear - do users wear mask or other protective gear

**Comment by cankisagun** [comment]
Suggestions for symptom reporting to include the following points:
- fever (we can add different levels-<100 F or >102 F)
- cough: severity
- loss of smell, taste 
- sore throat
- muscle pain
- appetite loss
in every category can be added numbers of days since symptoms started

After symptoms we can ask how many people live with that person, so we will find more easily new contacts. 

Symptoms are pretty important, you will not get tested without symptoms and from the last studies we can say that 40% of people infected have mild or moderate symptoms. That's why #selterinplace or #stayhome laws

cc @ainsleys 

EDIT: Here are how symptoms can be classified as high risk
- Fever +102 (38.5 Celsius)
- Dry cough over 2 days (losing breath)
- Sore throat (like fire in the neck)

**Comment by kistn010** [comment]
Symptoms commonly reported by patients with COVID-19 include fever (temperature ≥100.4F/38C), cough, shortness of breath (dyspnea). [Citation](https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html).
 
In adults, emergency warning signs for COVID-19 may include difficulty breathing, persistent pain or pressure in the chest, new confusion or an inability to arouse, or blueness of the lips or face. [Citation](https://www.cdc.gov/coronavirus/2019-ncov/if-you-are-sick/care-for-someone.html#monitor).

Neither list is all-inclusive.
It's worth noting that the language used by the CDC to describe the signs/symptoms for COVID-19 has remained the same throughout the agency's campaign.

**Comment by kistn010** [comment]
> Symptoms commonly reported by patients with COVID-19 include fever (temperature ≥100.4F/38C), cough, shortness of breath (dyspnea). [Citation](https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html).
> 
> In adults, emergency warning signs for COVID-19 may include difficulty breathing, persistent pain or pressure in the chest, new confusion or an inability to arouse, or blueness of the lips or face. [Citation](https://www.cdc.gov/coronavirus/2019-ncov/if-you-are-sick/care-for-someone.html#monitor).
> 
> Neither list is all-inclusive.
> It's worth noting that the language used by the CDC to describe the signs/symptoms for COVID-19 has remained the same throughout the agency's campaign.

**Comment by ainsleys** [comment]
For further discussion of symptom reporting see #34 . Closing this issue as the inputs for MVP have been finalize, we'll make a new issue if we decide to update that in a subsequent version
