### ISSUE TITLE
I don't understand anything. Is this an app?

### ISSUE THREAD

**Issue by E3V3A** [enigmampc/SafeTrace#26]
Is this an app or something else? how do you run this thing?

**Comment by ainsleys** [comment]
Hey @E3V3A 
This is primarily a backend application which is capable of doing both storage and compute tasks on data submitted via an API. That application is rust code which runs inside of an intel sgx eclave, and compares user-submitted data to find matches. Note, this means that neither the server operator nor other users have access to plaintext user data. That work is under construction here: https://github.com/enigmampc/SafeTrace/tree/master/enclave/safetrace

We have scaffolding in place for a sample front-end, as well as UI wireframes that demonstrate the user experience of using the system. Any client app, however, should be able to leverage the backend services via the API, provided the data provided is in the correct format. The API is in-progress but documented here: https://github.com/enigmampc/SafeTrace/tree/master/api-server

Our MVP goal is to have a sample application that users can interact with via web browser, as well as functioning API that other applications can interact with as well. Hope that answers your questions, feel free to clarify them if not.

**Comment by cankisagun** [comment]
@E3V3A here's an executive summary we put together
https://bit.ly/3469aS9
