### ISSUE TITLE
PR from external

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/SafeTrace#28]
This issue is to resolve any problems with creating branches and PR from collaborators. 

 @shenrene we tested this and it looks like external collaborators *are* able to make PRs-- see: https://github.com/enigmampc/SafeTrace/pull/27

Can you let me know how you're trying to do it and what error you're seeing

**Comment by ainsleys** [comment]
@shenrene the procedure is, fork this repository, make your changes, and then submit changes as a PR here. LMK if this isn't working and at what stage you are having issues!

**Comment by assafmo** [comment]
@shenrene Also on this repo in the GitHub website you can "edit" files and GitHub will automatically fork this repo to your account. The changes you make will be applied on your fork.

![Screenshot from 2020-03-30 16-52-37](https://user-images.githubusercontent.com/22766533/77920242-e75d2400-72a6-11ea-860b-3a8e501fe37b.png)

**Comment by ainsleys** [comment]
Thanks @assafmo -- I'm closing this b/c we resolved the issue and got @shenrene 's PR brought in. Yay!
