### ISSUE TITLE
Full stack web support

### ISSUE THREAD

**Issue by cankisagun** [enigmampc/SafeTrace#3]
We need to build a web application that enables users to:
1) create username and password and unique IDs to be used for TEE computations
2) communicate to Enigma secret compute API (secret compute JSON RPC end points ) to locally encrypt user data. Inputs are <<user_ID, time_stamp, location history, covid-status). See the [following issue](https://github.com/enigmampc/SafeTrace/issues/18)
3) query Enigma secret compute API based on unique IDs (when users are signed in) to provide users individual reporting outcomes
4) Use google maps (or other maps API) to determine place name from lat / lon output of step 3
5) Host a maps API to create heat map for global view

**Comment by ainsleys** [comment]
Closing this as we now have front-end UI work in review in https://github.com/enigmampc/SafeTrace/pull/50
