### ISSUE TITLE
buildgen make file issue

### ISSUE THREAD

**Issue by CTONishantBijani** [enigmampc/SafeTrace#41]
Hello Enigmampc,

i am building server and found this :

bindgen Enclave_t.h --default-enum-style=rust --rust-target=nightly --no-recursive-whitelist --use-array-pointers-in-arguments --whitelist-function ocall_.* --raw-line "#![allow(dead_code)] use enigma_types::*; use sgx_types::*;" -- -I/home/nishant/.sgxsdk/sgxsdk/include -I/home/nishant/Nishant/incubator-teaclave-sgx-sdk-master/edl > src/auto_ffi.rs
/bin/sh: 1: bindgen: not found
Makefile:34: recipe for target 'bindgen' failed
make[1]: *** [bindgen] Error 127

Here i can see from Make file that buildgen is target and we are using buildgen as executer as well. am i missing here anything?

**Comment by CTONishantBijani** [comment]
using cargo need to install. i was trying with apt install. closing this issue.

**Comment by ainsleys** [comment]
Thank you for updating us on how you resolved this, @Embedded4development . Feel free to open a PR for README or documentation if there is something we can be more clear about that will help others not run into the same speedbump.

**Comment by lacabra** [comment]
Thanks @Embedded4development for reporting this. Yes, I have on my ToDo list to build the documentation on how to properly have an environment setup. In the meantime, if anyone else encounters this issue, it is fixed by running:
```bash
cargo install bindgen
```
