### ISSUE TITLE
Why does the MVP return the location of a match rather than just the existence of a match?

### ISSUE THREAD

**Issue by FishmanL** [enigmampc/SafeTrace#53]
enclave code should be returning a binary for whether there exists a match or not -- this is average-case more efficient (since you can break out of the loop as soon as you find a match) as well as less leaky on the info side.

**Comment by ainsleys** [comment]
Our thinking is users / client apps get important information about risk from knowing some information about the match. I.e., a match in a small cafe > risk than a match in an open park.

**Comment by cankisagun** [comment]
Leor, when and where is important.
- If you know where you had a high risk interaction, you can let ppl know who were potentially with you at that time 
- If you know when you had a high risk interaction, you can let ppl know whom you've been with after (importance of time)

**Comment by FishmanL** [comment]
Alright, fair

**Comment by cankisagun** [comment]
Closing the issue as we think it's resolved
