### ISSUE TITLE
please add Ryerson University team from Toronto, Canada

### ISSUE THREAD

**Issue by justintoronto** [enigmampc/SafeTrace#74]
Hi Can,

Can you please add these users as Contributors?
We have spoken to Can Kisagun and told us to raise a GitHub issue.

We would like to get the IBM RPC Server credentials in the Client and API

Ryerson University Team
justin.keswick@gmail.com
a.mehran@gmail.com
justintoronto@hotmail.com
maksym.brylkov@gmail.com 
mark.donaldson@ryerson.ca 

const zmq = require("zeromq");
const cors = require('cors');
const jayson = require("jayson");
const crypto = require('crypto');
const connect = require('connect');
const bodyParser = require('body-parser');

const app = connect();
const socket = zmq.socket('req');
const ENCLAVE_URI = 'tcp://localhost:5552';
const _INVALID_PARAM = -32602;

Thank you,
Justin Keswick
Cell 647-563-1045
Toronto, Ontario, Canada

Can Kisagun
Cofounder 
www.enigma.co | Start building with Enigma

**Comment by cankisagun** [comment]
@lacabra can you pls help with RPC server credentials?

**Comment by lacabra** [comment]
Hi @justintoronto, thanks for your interest in contributing to SafeTrace 💪

I am not sure I understand your request:

1. Anyone can submit contributions to this public repository. Can you please clarify what you mean by adding these users are contributors? They are all welcome to fork this repo, make contributions and submit a Pull Request (PR) like others are actively doing already.

2. Kindly explain what do you mean by "We would like to get the IBM RPC Server credentials in the Client and API". The RPC Server is publicly available. Anyone can query it and interact with it directly. Its address is https://safetrace.enigma.co/. What credentials do you need?

**Comment by justintoronto** [comment]
Hi Can and Victor,

So replace the localhost with safetrace.enigma.co? I remember reading that
in the notes that the server only responds on a certain port.
Thanks again for the call yesterday. We simply needed the server name. No
credentials required.

 https://safetrace.enigma.co/

We will not be forking your code in the short term. Our approach is more to
identify where hot spots are locally in Ontario, Canada.
We have latitude and longitude data of testing centers. The goal is to get
more granular for the heat maps.
In Canada, we identify hot spots with Postal Codes.

We can stay in touch by SMS while we determine next steps.

Thank you again,

Justin Keswick

**Comment by lacabra** [comment]
@justintoronto: Yes, that is correct, replace `localhost` with https://safetrace.enigma.co/.

As a matter of fact, this replacement has just been pushed to the code in PR #76 

Closing this issue as seems resolved. Feel free to reopen otherwise.
