### ISSUE TITLE
enigma-core dependency is archived; is there a replacement?

### ISSUE THREAD

**Issue by sbellem** [enigmampc/SafeTrace#92]
I'd like to understand if something is replacing the enigma-core library, which is a dependency for SafeTrace. I could not find information on the repository README of enigma-core, and it's not possible to create new issues. Hence, I am asking here in the hope to better understand the on-going development of SafeTrace and its `enigma-core` dependency.

**Comment by assafmo** [comment]
The enigma-core code is good but archived because we've moved development to https://github.com/enigmampc/SecretNetwork. So for now I think It's fine.

**Comment by sbellem** [comment]
Thanks for the information!
